routes/web.php
<?php

use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'users');
Route::resource('users', UsersController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'phone',
        'polyclinic',
        'theme',
        'message',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Models\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('id', 'desc')->get();
        return view('index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        return view('form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request)
    {
        $countPhone = User::where('phone', $request['phone'])->get()->count();

        if ($countPhone != 0) {
            $countСoincidence = User::where('phone', $request['phone'])->where('name', $request['name'])->get()->count();
            if ($countСoincidence != 1) {
                $messageWarning = "Пользователь с телефоном {$request['phone']} уже существует!";
                return view('form', ['messageWarning' => $messageWarning]);
            }
        } else {
            User::create($request->only(['name', 'phone', 'polyclinic', 'theme', 'message']));
            return redirect()->route('users.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\User $user
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\User $user
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('form', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/form.blade.php
@extends('layout')
@section('title', 'Создать сообщение')

@section('content')
    @if(isset($messageWarning))
        <h4 class="text-danger">{{ $messageWarning }}</h4>
    @endif
    <a class="btn btn-primary mt-3 mb-3" role="button" href="{{ route('users.index') }}">Список сообщений</a>
    <form method="POST" action="{{ route('users.store') }}" class="row g-3">
        @csrf
        <div class="col-12">
            <label for="inputName" class="form-label">ФИО</label>
            <input name="name" value="{{ old('name') }}" type="text" class="form-control" id="inputName"
                   placeholder="Введите ФИО">
            @error('name')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="col-12">
            <label for="inputPhone" class="form-label">Телефон</label>
            <input name="phone" value="{{ old('phone') }}" type="text" class="form-control" id="inputPhone"
                   placeholder="+7 000 000-00-00">
            @error('phone')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="col-12">
            <label for="inputPolyclinic" class="form-label">Поликлиника</label>
            <input name="polyclinic" value="{{ old('polyclinic') }}" type="text" class="form-control"
                   id="inputPolyclinic" placeholder="Название поликлиники">
            @error('polyclinic')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="col-12">
            <label class="form-label" for="inputTheme">Тема</label>
            <select name="theme" class="form-select" id="inputTheme">
                <option selected>Выберете...</option>
                <option value="Запрос на изменение" {{ old('theme') == 'Запрос на изменение' ? 'selected' : '' }}>Запрос
                    на изменение
                </option>
                <option value="Инцидент" {{ old('theme') == 'Инцидент' ? 'selected' : '' }}>Инцидент</option>
                <option value="Разработка" {{ old('theme') == 'Разработка' ? 'selected' : '' }}>Разработка</option>
                <option value="Другое" {{ old('theme') == 'Другое' ? 'selected' : '' }}>Другое</option>
            </select>
            @error('theme')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="col-12">
            <label for="inputMessage" class="form-label">Сообщение</label>
            <textarea name="message" class="form-control" id="inputMessage" placeholder="Введите текст" cols="50"
                      rows="5">{{ old('message') }}</textarea>
            @error('message')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Добавить</button>
        </div>
    </form>
@endsection

resources/views/index.blade.php
@extends('layout')

@section('title', 'Сообщения')

@section('content')
    <a class="btn btn-primary" role="button" href="{{ route('users.create') }}">Добавить сообщение</a>

    @foreach($users as $user)
        <div class="card mt-3">
            <div class="card-header">
                {{ $user->name }}
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ $user->phone }}</li>
                <li class="list-group-item">{{ $user->polyclinic }}</li>
                <li class="list-group-item">{{ $user->theme }}</li>
                <li class="list-group-item">{{ $user->message }}</li>
            </ul>
        </div>
    @endforeach
@endsection

resources/views/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title')</title>


    <link href="https://getbootstrap.com/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/5.2/examples/checkout/form-validation.css" rel="stylesheet">
</head>
<body class="bg-light">

<div class="container">
    <h1 class="mx-auto">@yield('title')</h1>
    <main>
        @yield('content')
    </main>
</div>

<script src="https://getbootstrap.com/docs/5.2/examples/checkout/form-validation.js"></script>
</body>
</html>

resources/views/show.blade.php
@extends('layout')
@section('title', 'Users')

@section('content')

@endsection